// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: internal/conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_internal_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_internal_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Mysql         map[string]*MysqlDBConfig `protobuf:"bytes,1,rep,name=mysql,proto3" json:"mysql,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Redis         map[string]*RedisDBConfig `protobuf:"bytes,2,rep,name=redis,proto3" json:"redis,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Jwt           *JwtConfig                `protobuf:"bytes,3,opt,name=jwt,proto3" json:"jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_internal_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetMysql() map[string]*MysqlDBConfig {
	if x != nil {
		return x.Mysql
	}
	return nil
}

func (x *Data) GetRedis() map[string]*RedisDBConfig {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Data) GetJwt() *JwtConfig {
	if x != nil {
		return x.Jwt
	}
	return nil
}

type MysqlDBConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Master        *MysqlDBConfig_Master  `protobuf:"bytes,1,opt,name=master,proto3" json:"master,omitempty"`
	Slaves        []*MysqlDBConfig_Slave `protobuf:"bytes,2,rep,name=slaves,proto3" json:"slaves,omitempty"`
	MaxIdle       int64                  `protobuf:"varint,3,opt,name=max_idle,json=maxIdle,proto3" json:"max_idle,omitempty"`
	MaxOpen       int64                  `protobuf:"varint,4,opt,name=max_open,json=maxOpen,proto3" json:"max_open,omitempty"`
	MaxLifetime   int64                  `protobuf:"varint,5,opt,name=max_lifetime,json=maxLifetime,proto3" json:"max_lifetime,omitempty"`
	IsDebug       bool                   `protobuf:"varint,6,opt,name=is_debug,json=isDebug,proto3" json:"is_debug,omitempty"`
	SslEnable     bool                   `protobuf:"varint,7,opt,name=ssl_enable,json=sslEnable,proto3" json:"ssl_enable,omitempty"`
	CaFile        string                 `protobuf:"bytes,8,opt,name=ca_file,json=caFile,proto3" json:"ca_file,omitempty"`
	TlsName       string                 `protobuf:"bytes,9,opt,name=tls_name,json=tlsName,proto3" json:"tls_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MysqlDBConfig) Reset() {
	*x = MysqlDBConfig{}
	mi := &file_internal_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MysqlDBConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlDBConfig) ProtoMessage() {}

func (x *MysqlDBConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlDBConfig.ProtoReflect.Descriptor instead.
func (*MysqlDBConfig) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *MysqlDBConfig) GetMaster() *MysqlDBConfig_Master {
	if x != nil {
		return x.Master
	}
	return nil
}

func (x *MysqlDBConfig) GetSlaves() []*MysqlDBConfig_Slave {
	if x != nil {
		return x.Slaves
	}
	return nil
}

func (x *MysqlDBConfig) GetMaxIdle() int64 {
	if x != nil {
		return x.MaxIdle
	}
	return 0
}

func (x *MysqlDBConfig) GetMaxOpen() int64 {
	if x != nil {
		return x.MaxOpen
	}
	return 0
}

func (x *MysqlDBConfig) GetMaxLifetime() int64 {
	if x != nil {
		return x.MaxLifetime
	}
	return 0
}

func (x *MysqlDBConfig) GetIsDebug() bool {
	if x != nil {
		return x.IsDebug
	}
	return false
}

func (x *MysqlDBConfig) GetSslEnable() bool {
	if x != nil {
		return x.SslEnable
	}
	return false
}

func (x *MysqlDBConfig) GetCaFile() string {
	if x != nil {
		return x.CaFile
	}
	return ""
}

func (x *MysqlDBConfig) GetTlsName() string {
	if x != nil {
		return x.TlsName
	}
	return ""
}

type RedisDBConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,3,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,4,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	Db            int32                  `protobuf:"varint,5,opt,name=db,proto3" json:"db,omitempty"`
	SslEnable     bool                   `protobuf:"varint,6,opt,name=ssl_enable,json=sslEnable,proto3" json:"ssl_enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedisDBConfig) Reset() {
	*x = RedisDBConfig{}
	mi := &file_internal_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisDBConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisDBConfig) ProtoMessage() {}

func (x *RedisDBConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisDBConfig.ProtoReflect.Descriptor instead.
func (*RedisDBConfig) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *RedisDBConfig) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *RedisDBConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RedisDBConfig) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *RedisDBConfig) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

func (x *RedisDBConfig) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

func (x *RedisDBConfig) GetSslEnable() bool {
	if x != nil {
		return x.SslEnable
	}
	return false
}

type JwtConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Expire        int32                  `protobuf:"varint,2,opt,name=expire,proto3" json:"expire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwtConfig) Reset() {
	*x = JwtConfig{}
	mi := &file_internal_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwtConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtConfig) ProtoMessage() {}

func (x *JwtConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtConfig.ProtoReflect.Descriptor instead.
func (*JwtConfig) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *JwtConfig) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *JwtConfig) GetExpire() int32 {
	if x != nil {
		return x.Expire
	}
	return 0
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_internal_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Server_HTTP) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_internal_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Server_GRPC) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type MysqlDBConfig_Master struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dsn           string                 `protobuf:"bytes,1,opt,name=dsn,proto3" json:"dsn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MysqlDBConfig_Master) Reset() {
	*x = MysqlDBConfig_Master{}
	mi := &file_internal_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MysqlDBConfig_Master) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlDBConfig_Master) ProtoMessage() {}

func (x *MysqlDBConfig_Master) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlDBConfig_Master.ProtoReflect.Descriptor instead.
func (*MysqlDBConfig_Master) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{3, 0}
}

func (x *MysqlDBConfig_Master) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

type MysqlDBConfig_Slave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dsn           string                 `protobuf:"bytes,1,opt,name=dsn,proto3" json:"dsn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MysqlDBConfig_Slave) Reset() {
	*x = MysqlDBConfig_Slave{}
	mi := &file_internal_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MysqlDBConfig_Slave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlDBConfig_Slave) ProtoMessage() {}

func (x *MysqlDBConfig_Slave) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlDBConfig_Slave.ProtoReflect.Descriptor instead.
func (*MysqlDBConfig_Slave) Descriptor() ([]byte, []int) {
	return file_internal_conf_conf_proto_rawDescGZIP(), []int{3, 1}
}

func (x *MysqlDBConfig_Slave) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

var File_internal_conf_conf_proto protoreflect.FileDescriptor

const file_internal_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x18internal/conf/conf.proto\x12\agin.api\x1a\x1egoogle/protobuf/duration.proto\"W\n" +
	"\tBootstrap\x12'\n" +
	"\x06server\x18\x01 \x01(\v2\x0f.gin.api.ServerR\x06server\x12!\n" +
	"\x04data\x18\x02 \x01(\v2\r.gin.api.DataR\x04data\"\xda\x02\n" +
	"\x06Server\x12(\n" +
	"\x04http\x18\x01 \x01(\v2\x14.gin.api.Server.HTTPR\x04http\x12(\n" +
	"\x04grpc\x18\x02 \x01(\v2\x14.gin.api.Server.GRPCR\x04grpc\x1a}\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x1a}\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\"\xb0\x02\n" +
	"\x04Data\x12.\n" +
	"\x05mysql\x18\x01 \x03(\v2\x18.gin.api.Data.MysqlEntryR\x05mysql\x12.\n" +
	"\x05redis\x18\x02 \x03(\v2\x18.gin.api.Data.RedisEntryR\x05redis\x12$\n" +
	"\x03jwt\x18\x03 \x01(\v2\x12.gin.api.JwtConfigR\x03jwt\x1aP\n" +
	"\n" +
	"MysqlEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.gin.api.MysqlDBConfigR\x05value:\x028\x01\x1aP\n" +
	"\n" +
	"RedisEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.gin.api.RedisDBConfigR\x05value:\x028\x01\"\xfa\x02\n" +
	"\rMysqlDBConfig\x125\n" +
	"\x06master\x18\x01 \x01(\v2\x1d.gin.api.MysqlDBConfig.MasterR\x06master\x124\n" +
	"\x06slaves\x18\x02 \x03(\v2\x1c.gin.api.MysqlDBConfig.SlaveR\x06slaves\x12\x19\n" +
	"\bmax_idle\x18\x03 \x01(\x03R\amaxIdle\x12\x19\n" +
	"\bmax_open\x18\x04 \x01(\x03R\amaxOpen\x12!\n" +
	"\fmax_lifetime\x18\x05 \x01(\x03R\vmaxLifetime\x12\x19\n" +
	"\bis_debug\x18\x06 \x01(\bR\aisDebug\x12\x1d\n" +
	"\n" +
	"ssl_enable\x18\a \x01(\bR\tsslEnable\x12\x17\n" +
	"\aca_file\x18\b \x01(\tR\x06caFile\x12\x19\n" +
	"\btls_name\x18\t \x01(\tR\atlsName\x1a\x1a\n" +
	"\x06Master\x12\x10\n" +
	"\x03dsn\x18\x01 \x01(\tR\x03dsn\x1a\x19\n" +
	"\x05Slave\x12\x10\n" +
	"\x03dsn\x18\x01 \x01(\tR\x03dsn\"\xec\x01\n" +
	"\rRedisDBConfig\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12<\n" +
	"\fread_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x12\x0e\n" +
	"\x02db\x18\x05 \x01(\x05R\x02db\x12\x1d\n" +
	"\n" +
	"ssl_enable\x18\x06 \x01(\bR\tsslEnable\";\n" +
	"\tJwtConfig\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x16\n" +
	"\x06expire\x18\x02 \x01(\x05R\x06expireB7Z5github.com/buqiuwenda/gin-template/internal/conf;confb\x06proto3"

var (
	file_internal_conf_conf_proto_rawDescOnce sync.Once
	file_internal_conf_conf_proto_rawDescData []byte
)

func file_internal_conf_conf_proto_rawDescGZIP() []byte {
	file_internal_conf_conf_proto_rawDescOnce.Do(func() {
		file_internal_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_conf_conf_proto_rawDesc), len(file_internal_conf_conf_proto_rawDesc)))
	})
	return file_internal_conf_conf_proto_rawDescData
}

var file_internal_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),            // 0: gin.api.Bootstrap
	(*Server)(nil),               // 1: gin.api.Server
	(*Data)(nil),                 // 2: gin.api.Data
	(*MysqlDBConfig)(nil),        // 3: gin.api.MysqlDBConfig
	(*RedisDBConfig)(nil),        // 4: gin.api.RedisDBConfig
	(*JwtConfig)(nil),            // 5: gin.api.JwtConfig
	(*Server_HTTP)(nil),          // 6: gin.api.Server.HTTP
	(*Server_GRPC)(nil),          // 7: gin.api.Server.GRPC
	nil,                          // 8: gin.api.Data.MysqlEntry
	nil,                          // 9: gin.api.Data.RedisEntry
	(*MysqlDBConfig_Master)(nil), // 10: gin.api.MysqlDBConfig.Master
	(*MysqlDBConfig_Slave)(nil),  // 11: gin.api.MysqlDBConfig.Slave
	(*durationpb.Duration)(nil),  // 12: google.protobuf.Duration
}
var file_internal_conf_conf_proto_depIdxs = []int32{
	1,  // 0: gin.api.Bootstrap.server:type_name -> gin.api.Server
	2,  // 1: gin.api.Bootstrap.data:type_name -> gin.api.Data
	6,  // 2: gin.api.Server.http:type_name -> gin.api.Server.HTTP
	7,  // 3: gin.api.Server.grpc:type_name -> gin.api.Server.GRPC
	8,  // 4: gin.api.Data.mysql:type_name -> gin.api.Data.MysqlEntry
	9,  // 5: gin.api.Data.redis:type_name -> gin.api.Data.RedisEntry
	5,  // 6: gin.api.Data.jwt:type_name -> gin.api.JwtConfig
	10, // 7: gin.api.MysqlDBConfig.master:type_name -> gin.api.MysqlDBConfig.Master
	11, // 8: gin.api.MysqlDBConfig.slaves:type_name -> gin.api.MysqlDBConfig.Slave
	12, // 9: gin.api.RedisDBConfig.read_timeout:type_name -> google.protobuf.Duration
	12, // 10: gin.api.RedisDBConfig.write_timeout:type_name -> google.protobuf.Duration
	12, // 11: gin.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	12, // 12: gin.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	3,  // 13: gin.api.Data.MysqlEntry.value:type_name -> gin.api.MysqlDBConfig
	4,  // 14: gin.api.Data.RedisEntry.value:type_name -> gin.api.RedisDBConfig
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_internal_conf_conf_proto_init() }
func file_internal_conf_conf_proto_init() {
	if File_internal_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_conf_conf_proto_rawDesc), len(file_internal_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_conf_conf_proto_goTypes,
		DependencyIndexes: file_internal_conf_conf_proto_depIdxs,
		MessageInfos:      file_internal_conf_conf_proto_msgTypes,
	}.Build()
	File_internal_conf_conf_proto = out.File
	file_internal_conf_conf_proto_goTypes = nil
	file_internal_conf_conf_proto_depIdxs = nil
}
