// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package web

import (
	"github.com/buqiuwenda/gin-template/internal/application/user"
	"github.com/buqiuwenda/gin-template/internal/config"
	"github.com/buqiuwenda/gin-template/internal/data"
	datauser "github.com/buqiuwenda/gin-template/internal/data/user"
	"github.com/buqiuwenda/gin-template/internal/server"
	transportuser "github.com/buqiuwenda/gin-template/internal/transport/http/v1/user"
)

// Injectors from wire.go:

func InitializeHTTPServer(configPath2 string) (*server.HTTPServer, func(), error) {
	configConfig, err := config.New(configPath2)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(configConfig)
	if err != nil {
		return nil, nil, err
	}
	db := data.ProvideDB(dataData)
	repository := datauser.NewUserRepository(db)
	service := user.NewService(repository)
	handler := transportuser.NewHandler(service)
	engine := server.NewRouter(configConfig, handler)
	httpServer := server.NewHTTPServer(configConfig, engine)
	return httpServer, func() {
		cleanup()
	}, nil
}
