// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package web

import (
	"github.com/buqiuwenda/gin-template/internal/app"
	user2 "github.com/buqiuwenda/gin-template/internal/application/user"
	"github.com/buqiuwenda/gin-template/internal/config"
	"github.com/buqiuwenda/gin-template/internal/data/user"
	"github.com/buqiuwenda/gin-template/internal/server"
	user3 "github.com/buqiuwenda/gin-template/internal/transport/http/v1/user"
)

// Injectors from wire.go:

func InitializeApp(configPath2 string) (*app.App, func(), error) {
	configConfig, err := config.New(configPath2)
	if err != nil {
		return nil, nil, err
	}
	repository := user.NewRepository()
	service := user2.NewService(repository)
	handler := user3.NewHandler(service)
	engine := server.NewRouter(configConfig, handler)
	httpServer := server.NewHTTPServer(configConfig, engine)
	appApp := app.New(httpServer)
	return appApp, func() {
	}, nil
}
