syntax = "proto3";

package api.v1.user;

import "google/api/annotations.proto";

option go_package = "github.com/buqiuwenda/gin-template/api/v1/user;userv1";

service UserService {
  rpc CreateUser(CreateUserRequest) returns (CreateUserReply) {
    option (google.api.http) = {
      post: "/api/v1/users"
      body: "*"
    };
  }
  rpc GetUser(GetUserRequest) returns (GetUserReply) {
    option (google.api.http) = {
      get: "/api/v1/users/{id}"
    };
  }
}

message CreateUserRequest {
  string username = 1;
  string email = 2;
  string password = 3;
}

message CreateUserReply {
  User user = 1;
}

message GetUserRequest {
  uint64 id = 1;
}

message GetUserReply {
  User user = 1;
}

message User {
  uint64 id = 1;
  string username = 2;
  string email = 3;
}
